<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TelecomSupportSystem.Application\TelecomSupportSystem.Application.csproj" />
    <ProjectReference Include="..\TelecomSupportSystem.Domain\TelecomSupportSystem.Domain.csproj" />
  </ItemGroup>

</Project>
